version: '2.3'

services:
  redis:
    restart: always
    image: redis:6.2.6
    command:
    - --loglevel warning
    volumes:
    - redis-data:/data:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:14-20230628
    volumes:
    - postgresql-data:/var/lib/postgresql:Z
    env_file:
    - .env.pgsql
    shm_size: 512mb

  gitlab:
    restart: always
    image: sameersbn/gitlab:16.7.3
    depends_on:
    - redis
    - postgresql
    ports:
    - "1080:80"
    - "10022:22"
    volumes:
    - gitlab-data:/home/git/data:Z
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    env_file:
      - path: ./variables.env
        required: true # default

volumes:
  redis-data:
  postgresql-data:
  gitlab-data:
